---
title: "Tutorial: Simulate Tree Rings"
author: "Daniel J. Hocking & Laura G. Smith"
date: "`r Sys.Date()`"
output:
      rmarkdown::html_vignette:
        fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Tutorial: Simulate Tree Rings}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, fig.show='hold', echo=FALSE, eval=FALSE}
# The figure sizes have been customised so that you can easily put two images side-by-side.
plot(1:10)
plot(10:1)

# Yyou can use the chunk option `fig.cap = "Your figure caption."`
```


```{r, echo=FALSE, results='asis', eval=FALSE}
# tables, e.g. using `knitr::kable()`.
knitr::kable(head(mtcars, 10))
```

```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(devtools)
install_github(repo = "lgsmith295/simDendro")
```


## Simulate Negative Exponential Growth

$$
rwl = biological \times climate \times error
$$

### Modified Negative Exponential

$$
rwl_{it} = ae^{-bt + k} e^{\beta \times climate}e^{error}
$$

$$
log(rwl_{it}) = \alpha - bt + \beta \times climate + error
$$

where $\alpha = log(a) + k$

$$
log(rwl_{it}) = \alpha_{0it} + \alpha_{1it} age_{it} + \beta X_{it} + \epsilon_{it}
$$


```{r, fig.width=8, fig.height=4}
library(simDendro)
years <- 1:50

# Growth
growth <- negexp_growth(length(years), 1, 0.03, 0.001)
plot(growth, type = "b")

# climate
mu_climate <- 12
climate <- rnorm(length(years), mu_climate, 3)
plot(climate, type = "l")

# Climate effect on growth
beta_mu <- 0.8 # real scale slope - 1 degree C increase in T results in this change in mm tree ring growth
# log_beta <- log(beta_mu)
beta <- rnorm(length(years), beta_mu, 0.05)
eta <- beta * climate
plot(eta, type = "l")
plot(climate, eta)

# IID error
eps <- rnorm(length(years), -2.5, 0.5)
error <- exp(eps)
summary(error)
plot(error, type = "l")

# Put growth model together
rwl <- growth * eta * error
plot(rwl, type = "b")

```

```{r, fig.width=8, fig.height=4}
library(simDendro)
years <- 1:50

# Growth
growth <- negexp_growth(length(years), 1, 0.03, 0.001)
plot(growth, type = "b")

# climate
mu_climate <- 10 + 0.1 * years
climate <- rnorm(length(years), mu_climate, 3)
plot(climate, type = "l")

# Climate effect on growth
beta_mu <- 0.8 # real scale slope - 1 degree C increase in T results in this change in mm tree ring growth
# log_beta <- log(beta_mu)
beta <- rnorm(length(years), beta_mu, 0.05)
eta <- beta * climate
plot(eta, type = "l")
plot(climate, eta)

# IID error
eps <- rnorm(length(years), -2.5, 0.5)
error <- exp(eps)
summary(error)
plot(error, type = "l")

# Put growth model together
rwl <- growth * eta * error
plot(rwl, type = "b")

```


